version: 2.1

orbs:
  auto: artsy/auto@2.2.0
  node: circleci/node@6.3.0

workflows:
  build_and_verify:
    jobs:
      - node/run:
          name: lint
          pkg-manager: yarn
          yarn-run: lint
          version: 18.15.0

      - node/run:
          name: type-check
          pkg-manager: yarn
          yarn-run: type-check
          version: 18.15.0

      - node/run:
          name: test
          pkg-manager: yarn
          yarn-run: test
          version: 18.15.0

      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore: main
          node-version: "16.10.0"
          requires:
            - test
            - lint
            - type-check

      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only: main
          node-version: "16.10.0"
          requires:
            - test
            - lint
            - type-check
